version: "3.9"

services:
  elasticsearch_another_ccr:
    platform: linux/x86_64
    image: elasticsearch:6.4.0
    volumes:
      - ./elastic_config/elasticsearch2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    restart: always
    ports:
      - "127.0.0.1:9201:9200"
      - "127.0.0.1:9301:9300"
    networks:
      - overlay
    environment:
      MY_VAR: value_here

  elasticsearch:
    platform: linux/x86_64
    image: elasticsearch:6.4.0
    volumes:
      - ./elastic_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic_data:/usr/share/elasticsearch/data
    restart: always
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    networks:
      - overlay
    environment:
      MY_VAR: value_here
  kibana:
    platform: linux/x86_64
    image: kibana:6.4.0
    ports:
      - "127.0.0.1:5601:5601"
    volumes:
      - ./elastic_config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - overlay
    depends_on:
          - elasticsearch

volumes:
  elastic_data: {}
  elastic_config: {}

networks:
  overlay: